source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~>1.1'
gem 'rspec', :require => 'spec'
gem 'whatlanguage'
gem 'mini_portile', '~> 0.6.2'
gem 'shoulda'
gem 'lda-ruby'
gem 'lyricfy'
gem 'csv2json'
gem 'pearson'